In [2]:
import scipy
import scipy.linalg   # SciPy Linear Algebra Library
import numpy as np

def dd(X):
    D = np.diag(np.abs(X)) # Find diagonal coefficients
    S = np.sum(np.abs(X), axis=1) - D # Find row sum without diagonal
    if np.all(D > S):
        print('matrix is diagonally dominant')
    else:
        print('NOT diagonally dominant')
    return


A = np.array([[2,3,1],[1,2,3],[3,1,2]])
dd(A);
P, L, U = scipy.linalg.lu(A)

print("A:")
print(A)

print("P:")
print(P)

print("L:")
print(L)

print("U:")
print(U)

NOT diagonally dominant
A:
[[2 3 1]
 [1 2 3]
 [3 1 2]]
P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.71428571 1.        ]]
U:
[[ 3.          1.          2.        ]
 [ 0.          2.33333333 -0.33333333]
 [ 0.          0.          2.57142857]]
