In [1]:
import numpy as np
import sys

### Function to calculate rank, eigen value and eigen vector of a matrix

In [2]:
def eigen(m):
    w,v = np.linalg.eig(m)
    R = np.linalg.matrix_rank(m)
    print("rank of matrix",(R))
    print('eigen values:',w)
    print('eigen vectors:',v)
    print('-----------------------------------------------------------')

### Function to find largest eigen value and eigen vector using power method

In [3]:
def power(a,x):
    print('-----------------------------------------------------------')
    print ('Power Method to find largest eigen value and eigen vector')

    n = int(len(a))

    tolerable_error = float(input('Enter tolerable error: '))


    max_iteration = int(input('Enter the number of iterations: '))
    
    # Power Method Implementation
    lambda_old = 1.0
    condition =  True
    step = 1
    while condition:
        # Multiplying a and x
        x = np.matmul(a,x)

        # Finding new Eigen value and Eigen vector
        lambda_new = max(abs(x))

        x = x/lambda_new

        # Displaying Eigen value and Eigen Vector
        print('\nIteration %d' %(step))
        print('-------------------')
        print('Maximum Eigen Value = %0.4f' %(lambda_new))
        print('Maximum Eigen Vector: ')
        for i in range(n):
            print('%0.3f\t' % (x[i]))

        # Checking maximum iteration
        step = step + 1
        if step > max_iteration:
            print('The given number of iteration is less than the maximum iteration.')
            break

        # Calculating error
        error = abs(lambda_new - lambda_old)
        print('error='+ str(error))
        lambda_old = lambda_new
        condition = error > tolerable_error

### Problem: 1

![image.png](problem_1.jpg)

In [4]:
a1=np.array([[2,1,-1],[4,-3,8],[1,0,2]])
x1=np.array([[1],[1],[1]])

In [5]:
eigen(a1)
power(a1,x1)

rank of matrix 3
eigen values: [ 3.          1.44948974 -3.44948974]
eigen vectors: [[-0.40824829 -0.31778265  0.17470271]
 [-0.81649658  0.7521937  -0.98409919]
 [-0.40824829  0.57725109 -0.03205855]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 9.0000
Maximum Eigen Vector: 
0.222	
1.000	
0.333	
error=[8.]

Iteration 2
-------------------
Maximum Eigen Value = 1.1111
Maximum Eigen Vector: 
1.000	
0.500	
0.800	
error=[7.88888889]

Iteration 3
-------------------
Maximum Eigen Value = 8.9000
Maximum Eigen Vector: 
0.191	
1.000	
0.292	
error=[7.78888889]

Iteration 4
-------------------
Maximum Eigen Value = 1.0899
Maximum Eigen Vector: 
1.000	
0.093	
0.711	
error=[7.81011236]

Iteration 5
-------------------
Maximum Eigen Value = 9.4124
M

### Problem: 2

![image.png](problem_2.jpg)

In [6]:
a2=np.array([[1.5,0,1],[-0.5,0.5,-0.5],[-0.5,0,0]])
x2=np.array([[1],[1],[1]])

In [7]:
eigen(a2)
power(a2,x2)

rank of matrix 3
eigen values: [0.5 1.  0.5]
eigen vectors: [[ 0.          0.81649658 -0.70710678]
 [ 1.         -0.40824829  0.        ]
 [ 0.         -0.40824829  0.70710678]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 2.5000
Maximum Eigen Vector: 
1.000	
-0.200	
-0.200	
error=[1.5]

Iteration 2
-------------------
Maximum Eigen Value = 1.3000
Maximum Eigen Vector: 
1.000	
-0.385	
-0.385	
error=[1.2]

Iteration 3
-------------------
Maximum Eigen Value = 1.1154
Maximum Eigen Vector: 
1.000	
-0.448	
-0.448	
error=[0.18461538]

Iteration 4
-------------------
Maximum Eigen Value = 1.0517
Maximum Eigen Vector: 
1.000	
-0.475	
-0.475	
error=[0.06366048]

Iteration 5
-------------------
Maximum Eigen Value = 1.0246
Maximum Eigen Vector: 


### Problem: 3

![image.png](problem_3.jpg)

In [8]:
a3=np.array([[4,2,1],[0,3,2],[1,1,4]])
x3=np.array([[1],[2],[1]])

In [9]:
eigen(a3)
power(a3,x3)

rank of matrix 3
eigen values: [5.91963957+0.j         2.54018022+0.68817282j 2.54018022-0.68817282j]
eigen vectors: [[-0.71357865+0.j          0.71828869+0.j          0.71828869-0.j        ]
 [-0.39592057+0.j         -0.51850636+0.38004717j -0.51850636-0.38004717j]
 [-0.57797268+0.j         -0.01155933-0.26578759j -0.01155933+0.26578759j]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 9.0000
Maximum Eigen Vector: 
1.000	
0.889	
0.778	
error=[8.]

Iteration 2
-------------------
Maximum Eigen Value = 6.5556
Maximum Eigen Vector: 
1.000	
0.644	
0.763	
error=[2.44444444]

Iteration 3
-------------------
Maximum Eigen Value = 6.0508
Maximum Eigen Vector: 
1.000	
0.571	
0.776	
error=[0.5047081]

Iteration 4
-------------------
Maximum Eigen V

### Problem: 4

![image.png](problem_4.jpg)

In [10]:
a4=np.array([[1,1,0,0],[1,2,0,1],[0,0,3,3],[0,1,3,2]])
x4=np.array([[1],[1],[0],[1]])

In [11]:
eigen(a4)
power(a4,x4)

rank of matrix 4
eigen values: [-0.80742669  0.4956877   2.6459269   5.6658121 ]
eigen vectors: [[-0.1791105  -0.8463097  -0.50004143 -0.04047077]
 [ 0.32372909  0.42680439 -0.82303164 -0.18882902]
 [ 0.57498299 -0.24469305  0.2675451  -0.73344358]
 [-0.7297352   0.2042626  -0.03157684 -0.65174092]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 4.0000
Maximum Eigen Vector: 
0.500	
1.000	
0.750	
0.750	
error=[3.]

Iteration 2
-------------------
Maximum Eigen Value = 4.7500
Maximum Eigen Vector: 
0.316	
0.684	
0.947	
1.000	
error=[0.75]

Iteration 3
-------------------
Maximum Eigen Value = 5.8421
Maximum Eigen Vector: 
0.171	
0.459	
1.000	
0.946	
error=[1.09210526]

Iteration 4
-------------------
Maximum Eigen Value = 5.8378
Maximum Eige

### Problem: 5

![image.png](problem_5.jpg)

In [12]:
a5=np.array([[5,-2,-1/2,3/2],[-2,5,3/2,-1/2],[-1/2,3/2,5,-2],[3/2,-1/2,-2,5]])
x5=np.array([[1],[1],[0],[-3]])

In [13]:
eigen(a5)
power(a5,x5)

rank of matrix 4
eigen values: [9. 2. 4. 5.]
eigen vectors: [[-0.5  0.5  0.5 -0.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 14.0000
Maximum Eigen Vector: 
-0.107	
0.321	
0.500	
-1.000	
error=[13.]

Iteration 2
-------------------
Maximum Eigen Value = 6.3214
Maximum Eigen Vector: 
-0.463	
0.486	
0.797	
-1.000	
error=[7.67857143]

Iteration 3
-------------------
Maximum Eigen Value = 7.5311
Maximum Eigen Vector: 
-0.689	
0.671	
0.922	
-1.000	
error=[1.20964487]

Iteration 4
-------------------
Maximum Eigen Value = 8.2123
Maximum Eigen Vector: 
-0.821	
0.805	
0.969	
-1.000	
error=[0.68122963]

Iteration 5
-------------------
Maximum Eigen Value = 8.5734
Maximum Eige

### Problem: 6

![image.png](problem_6.jpg)

In [14]:
a6=np.array([[-4,0,1/2,1/2],[1/2,-2,0,1/2],[1/2,1/2,0,0],[0,0,1,4]])
x6=np.array([[0],[0],[0],[1]])

In [15]:
eigen(a6)
power(a6,x6)

rank of matrix 4
eigen values: [-4.0407482  -2.00502085  0.02687328  4.01889577]
eigen vectors: [[-0.96663578 -0.04808705 -0.08967655  0.06314694]
 [ 0.23957501  0.97119828  0.03780294  0.08781534]
 [ 0.08996611 -0.23019991 -0.96515226  0.01878156]
 [-0.01118877  0.03833457  0.24292008  0.99395583]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 4.0000
Maximum Eigen Vector: 
0.125	
0.125	
0.000	
1.000	
error=[3.]

Iteration 2
-------------------
Maximum Eigen Value = 4.0000
Maximum Eigen Vector: 
0.000	
0.078	
0.031	
1.000	
error=[0.]


### Problem: 7

![image.png](problem_7.jpg)

In [16]:
a7=np.array([[-7,2],[8,-1]])
x7=np.array([[1],[1]])

In [17]:
eigen(a7)
power(a7,x7)

rank of matrix 2
eigen values: [-9.  1.]
eigen vectors: [[-0.70710678 -0.24253563]
 [ 0.70710678 -0.9701425 ]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 7.0000
Maximum Eigen Vector: 
-0.714	
1.000	
error=[6.]

Iteration 2
-------------------
Maximum Eigen Value = 7.0000
Maximum Eigen Vector: 
1.000	
-0.959	
error=[0.]


### Problem 8

![image.png](problem_8.jpg)

In [18]:
a8=np.array([[1,1,1,0],[1,2,0,1],[0,0,3,3],[0,1,3,2]])
x8=np.array([[1],[1],[0],[1]])

In [19]:
eigen(a8)
power(a8,x8)

rank of matrix 4
eigen values: [-0.89977467  0.7016587   2.50319962  5.69491635]
eigen vectors: [[ 0.45724599  0.81816063  0.39270544 -0.1992912 ]
 [-0.37775188 -0.48688983  0.87366618 -0.22637611]
 [-0.49091247  0.24279873 -0.28335151 -0.70927942]
 [ 0.63814934 -0.18601145  0.04692305 -0.63714957]]
-----------------------------------------------------------
-----------------------------------------------------------
Power Method to find largest eigen value and eigen vector
Enter tolerable error: 0.001
Enter the number of iterations: 100

Iteration 1
-------------------
Maximum Eigen Value = 4.0000
Maximum Eigen Vector: 
0.500	
1.000	
0.750	
0.750	
error=[3.]

Iteration 2
-------------------
Maximum Eigen Value = 4.7500
Maximum Eigen Vector: 
0.474	
0.684	
0.947	
1.000	
error=[0.75]

Iteration 3
-------------------
Maximum Eigen Value = 5.8421
Maximum Eigen Vector: 
0.360	
0.486	
1.000	
0.946	
error=[1.09210526]

Iteration 4
-------------------
Maximum Eigen Value = 5.8378
Maximum Eige