In [1]:
import numpy as np

In [2]:
def eigen(m):
    w,v = np.linalg.eig(m)
    print('eigen values:',w)
    print('eigen vectors:',v)

In [3]:
m= np.array([[2,1,-1],[4,3,8],[1,0,2]])
eigen(m)

eigen values: [5.+0.j         1.+1.41421356j 1.-1.41421356j]
eigen vectors: [[-2.86038777e-01+0.j         -4.08248290e-01-0.28867513j
  -4.08248290e-01+0.28867513j]
 [-9.53462589e-01+0.j          8.16496581e-01+0.j
   8.16496581e-01-0.j        ]
 [-9.53462589e-02+0.j         -8.32667268e-17+0.28867513j
  -8.32667268e-17-0.28867513j]]


In [4]:
n= np.array([[0,2,3],[4,0,6],[-7,8,9]])

In [5]:
eigen(n)

eigen values: [-3.90359683  1.32780944 11.5757874 ]
eigen vectors: [[ 0.02138332 -0.60714072  0.29735503]
 [-0.84447881 -0.75845379  0.51834665]
 [ 0.53516193  0.23691347  0.80180842]]


In [6]:
p=np.array([[2,-12],[1,-5]])

In [7]:
eigen(p)

eigen values: [-1. -2.]
eigen vectors: [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


## Algebric

In [20]:
def a(x):
    f=0.2+25*x-200*x**2+675*x**3-900*x**4+400*5
    return f

In [21]:
a(1.25)

840.04375

## Trigonometric

In [22]:
def f(x):
    t=x*np.sin(x)+np.cos(x)
    return t

In [23]:
x=[1,1.5]

In [27]:
f(x)

array([1.38177329, 1.56697968])

## Exponential

In [36]:
def e(x):
    l=np.cos(x)-x*np.exp(x)
    return l

In [40]:
e(1)

-2.1779795225909053

In [41]:
def rf(x0,x1):
    rr = (x0 * e(x1) - x1 * e(x0)) / (e(x1) - e(x0))
    return rr

In [42]:
rf(0.5,1)

0.5119267416577361