In [2]:
import numpy as np

In [3]:
import numpy.linalg as la

In [4]:
def power_method(mat, start, maxit):
    
    result = start
    for i in range(maxit):
        result = mat*result
        result = result/np.linalg.norm(result)
    return result

def check(mat, otp):
    
    prd = mat*otp
    eigval = prd[0]/otp[0]
    #print 'computed eigenvalue :' , eigval
    [eigs, vecs] = np.linalg.eig(mat)
    abseigs = list(abs(eigs))
    ind = abseigs.index(max(abseigs))
    print (' largest eigenvalue of A inverse :', eigs[ind])
    print('smallest eigen value :', 1/eigs[ind])
    
def main():
    
    #print 'Running the power method...'
    dim = input('Give the dimension : ')
    nbit = input('How many iterations ? ')
    dim = int(dim)
    nbit = int(nbit)
    j = complex(0, 1)
    rnd = np.random.normal(0, 1, (dim, dim)) \
        + np.random.normal(0, 1, (dim, dim))*j
    nbs = np.random.normal(0, 1, (dim, 1)) \
        + np.random.normal(0, 1, (dim, 1))*j
    rndmat = np.array([[2,1,-1],[4,3,8],[1,0,2]])
    inv = la.inv(rndmat)
    rndvec = np.matrix([[1],[1],[1]])
    eigmax = power_method(inv, rndvec, nbit)
    check(inv, eigmax)

main()

Give the dimension : 3
How many iterations ? 10
 largest eigenvalue of A inverse : (0.33333333333333337+0.47140452079103173j)
smallest eigen value : (0.9999999999999998-1.4142135623730947j)


In [4]:
t=np.array(([[2,1,-1],[4,3,8],[1,0,2]]))
t=la.inv(t)
x1=np.array(([[1],[1],[1]]))
Ax1=np.dot(t,x1)
Ax1

array([[0.2],
       [1. ],
       [0.4]])

In [5]:
x2=Ax1/max(np.dot(t,x1))
x2

array([[0.2],
       [1. ],
       [0.4]])

In [6]:
Ax2=np.dot(t,x2)
Ax2

array([[0.08],
       [0.2 ],
       [0.16]])

In [7]:
x3=Ax2/max(np.dot(t,x2))
x3

array([[0.4],
       [1. ],
       [0.8]])

In [8]:
Ax3=np.dot(t,x3)
Ax3

array([[0.02666667],
       [0.73333333],
       [0.38666667]])

In [9]:
x4=Ax3/max(np.dot(t,x3))
x4

array([[0.03636364],
       [1.        ],
       [0.52727273]])

In [10]:
Ax4=np.dot(t,x4)
Ax4

array([[-0.02787879],
       [ 0.36969697],
       [ 0.27757576]])

In [11]:
x5=Ax4/max(np.dot(t,x4))
x5

array([[-0.07540984],
       [ 1.        ],
       [ 0.75081967]])