In [1]:
import numpy as np

In [2]:
def power_method(mat, start, maxit):
    """
    Does maxit iterations of the power method
    on the matrix mat starting at start.
    Returns an approximation of the largest
    eigenvector of the matrix mat.
    """
    result = start
    for i in range(maxit):
        result = mat*result
        print('new eigenvector :' ,result)
        print('new eigenvalue :', np.linalg.norm(result))
        result = result/np.linalg.norm(result)
    return result

In [3]:
def check(mat, otp):
    """
    Compares the output otp of the power
    method with the largest eigenvalue
    of the matrix mat.
    """
    prd = mat*otp
    eigval = prd[0]/otp[0]
    print ('computed eigenvalue :' , eigval)
    [eigs, vecs] = np.linalg.eig(mat)
    abseigs = list(abs(eigs))
    ind = abseigs.index(max(abseigs))
    print (' largest eigenvalue :', eigs[ind])
    print (' largest eigenvector :', vecs[ind])

In [4]:
def main():
    """
    Prompts the user for a dimension
    and the number of iterations.
    """
    print ('Running the power method...')
    dim = int(input('Give the dimension : '))
    nbit = int(input('How many iterations ? '))
    j = complex(0, 1)
    #m=([[2,1,-1],[4,-3,8],[1,0,2]])
    t=np.array([[2,1,-1],[4,-3,8],[1,0,2]])
    nbs = np.random.normal(0, 1, (dim, 1)) + np.random.normal(0, 1, (dim, 1))
    rndmat = np.matrix(t)
    rndvec = np.matrix(nbs)
    eigmax = power_method(rndmat, rndvec, nbit)
    check(rndmat, eigmax)

In [5]:
#rnd = np.random.normal(0, 1, (dim, dim)) + np.random.normal(0, 1, (dim, dim))*j

    
main()


Running the power method...
Give the dimension : 3
How many iterations ? 5
new eigenvector : [[-5.98899925]
 [10.3533569 ]
 [ 1.21556016]]
new eigenvalue : 12.022383191512807
new eigenvector : [[-0.23624282]
 [-3.7672719 ]
 [-0.29593791]]
new eigenvalue : 3.786255075384535
new eigenvector : [[-1.04161488]
 [ 2.11009057]
 [-0.21871708]]
new eigenvalue : 2.363319901922942
new eigenvector : [[ 0.10391225]
 [-5.18189174]
 [-0.62583531]]
new eigenvalue : 5.220581342615833
new eigenvector : [[-0.83290186]
 [ 2.09835668]
 [-0.2198526 ]]
new eigenvalue : 2.268294831211183
computed eigenvalue : [[-0.78329222]]
 largest eigenvalue : -3.4494897427831774
 largest eigenvector : [[-0.40824829  0.57725109 -0.03205855]]


In [6]:
def main():
    """
    Prompts the user for a dimension
    and the number of iterations.
    """
    print ('Running the power method...')
    dim = int(input('Give the dimension : '))
    nbit = int(input('How many iterations ? '))
    j = complex(0, 1)
    #m=([[2,1,-1],[4,-3,8],[1,0,2]])
    t=np.array([[1.5,0,1],[-0.5,0.5,-0.5],[-0.5,0,0]])
    nbs = np.random.normal(0, 1, (dim, 1)) + np.random.normal(0, 1, (dim, 1))
    rndmat = np.matrix(t)
    rndvec = np.matrix(nbs)
    eigmax = power_method(rndmat, rndvec, nbit)
    check(rndmat, eigmax)

In [7]:
main()

Running the power method...
Give the dimension : 3
How many iterations ? 5
new eigenvector : [[-6.89128227]
 [ 1.6740407 ]
 [ 1.47351135]]
new eigenvalue : 7.243163623134652
new eigenvector : [[-1.22369347]
 [ 0.48955208]
 [ 0.47570942]]
new eigenvalue : 1.4012089087457864
new eigenvector : [[-0.9704697 ]
 [ 0.44159587]
 [ 0.43665633]]
new eigenvalue : 1.1521662686059246
new eigenvector : [[-0.88446282]
 [ 0.42329361]
 [ 0.42115002]]
new eigenvalue : 1.067154773135195
new eigenvector : [[-0.84855939]
 [ 0.41540667]
 [ 0.41440232]]
new eigenvalue : 1.0316709860570443
computed eigenvalue : [[1.01164018]]
 largest eigenvalue : 1.0
 largest eigenvector : [[ 1.         -0.40824829  0.        ]]


In [2]:
t=np.array([[2,1,-1],[4,-3,8],[1,0,2]])
x1=np.array([[1],[1],[1]])
Ax1=np.dot(t,x1)
Ax1

array([[2],
       [9],
       [3]])

In [3]:
x2=Ax1/max(np.dot(t,x1))
x2

array([[0.22222222],
       [1.        ],
       [0.33333333]])

In [4]:
Ax2=np.dot(t,x2)
Ax2

array([[1.11111111],
       [0.55555556],
       [0.88888889]])

In [5]:
x3=Ax2/max(np.dot(t,x2))
x3

array([[1. ],
       [0.5],
       [0.8]])

In [6]:
Ax3=np.dot(t,x3)
Ax3

array([[1.7],
       [8.9],
       [2.6]])

In [7]:
x4=Ax3/max(np.dot(t,x3))
x4

array([[0.19101124],
       [1.        ],
       [0.29213483]])

In [8]:
Ax4=np.dot(t,x4)
Ax4

array([[1.08988764],
       [0.1011236 ],
       [0.7752809 ]])

In [9]:
x5=Ax4/max(np.dot(t,x4))
x5

array([[1.        ],
       [0.09278351],
       [0.71134021]])